
package com.webservices.controladores.publicar;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebFault(name = "NombreRepetidoOfertaException", targetNamespace = "http://publicar.controladores/")
public class NombreRepetidoOfertaException_Exception
    extends Exception
{

    /**
	 * 
	 */
	private static final long serialVersionUID = 7445852803837817577L;
	/**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private NombreRepetidoOfertaException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public NombreRepetidoOfertaException_Exception(String message, NombreRepetidoOfertaException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param cause
     * @param faultInfo
     * @param message
     */
    public NombreRepetidoOfertaException_Exception(String message, NombreRepetidoOfertaException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: controladores.publicar.NombreRepetidoOfertaException
     */
    public NombreRepetidoOfertaException getFaultInfo() {
        return faultInfo;
    }

}
