
package com.webservices.controladores.publicar;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebFault(name = "NombrePaqueteYaExiste", targetNamespace = "http://publicar.controladores/")
public class NombrePaqueteYaExiste_Exception
    extends Exception
{

    /**
	 * 
	 */
	private static final long serialVersionUID = 6077598988834275293L;
	/**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private NombrePaqueteYaExiste faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public NombrePaqueteYaExiste_Exception(String message, NombrePaqueteYaExiste faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param cause
     * @param faultInfo
     * @param message
     */
    public NombrePaqueteYaExiste_Exception(String message, NombrePaqueteYaExiste faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: controladores.publicar.NombrePaqueteYaExiste
     */
    public NombrePaqueteYaExiste getFaultInfo() {
        return faultInfo;
    }

}
