
package com.webservices.controladores.publicar;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "PublicadorManejadorUsuario", targetNamespace = "http://publicar.controladores/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PublicadorManejadorUsuario {


    /**
     * 
     * @param arg0
     * @return
     *     returns controladores.publicar.DataEmpresa
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar.controladores/PublicadorManejadorUsuario/getDataEmpresaRequest", output = "http://publicar.controladores/PublicadorManejadorUsuario/getDataEmpresaResponse")
    public DataEmpresa getDataEmpresa(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns controladores.publicar.DataPostulante
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar.controladores/PublicadorManejadorUsuario/getDataPostulanteRequest", output = "http://publicar.controladores/PublicadorManejadorUsuario/getDataPostulanteResponse")
    public DataPostulante getDataPostulante(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns controladores.publicar.DataUsuario
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar.controladores/PublicadorManejadorUsuario/obtenerUsuarioRequest", output = "http://publicar.controladores/PublicadorManejadorUsuario/obtenerUsuarioResponse")
    public DataUsuario obtenerUsuario(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns controladores.publicar.WrapperArrayList
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar.controladores/PublicadorManejadorUsuario/obtenerOfertasConfirmadasDeEmpresaRequest", output = "http://publicar.controladores/PublicadorManejadorUsuario/obtenerOfertasConfirmadasDeEmpresaResponse")
    public WrapperArrayList obtenerOfertasConfirmadasDeEmpresa(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns controladores.publicar.DataUsuario
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar.controladores/PublicadorManejadorUsuario/obtenerUsuarioPorEmailRequest", output = "http://publicar.controladores/PublicadorManejadorUsuario/obtenerUsuarioPorEmailResponse")
    public DataUsuario obtenerUsuarioPorEmail(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns controladores.publicar.WrapperArrayList
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar.controladores/PublicadorManejadorUsuario/obtenerOfertasRechazadasIngresadasRequest", output = "http://publicar.controladores/PublicadorManejadorUsuario/obtenerOfertasRechazadasIngresadasResponse")
    public WrapperArrayList obtenerOfertasRechazadasIngresadas(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns controladores.publicar.WrapperArrayList
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar.controladores/PublicadorManejadorUsuario/obtenerOfertasDeUnaEmpresaRequest", output = "http://publicar.controladores/PublicadorManejadorUsuario/obtenerOfertasDeUnaEmpresaResponse")
    public WrapperArrayList obtenerOfertasDeUnaEmpresa(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @return
     *     returns controladores.publicar.WrapperHashMap
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar.controladores/PublicadorManejadorUsuario/getDataEmpresasRequest", output = "http://publicar.controladores/PublicadorManejadorUsuario/getDataEmpresasResponse")
    public WrapperHashMap getDataEmpresas();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @Action(input = "http://publicar.controladores/PublicadorManejadorUsuario/addUsuarioRequest", output = "http://publicar.controladores/PublicadorManejadorUsuario/addUsuarioResponse")
    public void addUsuario(
        @WebParam(name = "arg0", partName = "arg0")
        DataUsuario arg0);

    /**
     * 
     * @return
     *     returns controladores.publicar.WrapperHashMap
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar.controladores/PublicadorManejadorUsuario/getDataPostulantesRequest", output = "http://publicar.controladores/PublicadorManejadorUsuario/getDataPostulantesResponse")
    public WrapperHashMap getDataPostulantes();

    /**
     * 
     * @param arg0
     * @param arg1
     */
    @WebMethod(operationName = "CompraPaquete")
    @Action(input = "http://publicar.controladores/PublicadorManejadorUsuario/CompraPaqueteRequest", output = "http://publicar.controladores/PublicadorManejadorUsuario/CompraPaqueteResponse")
    public void compraPaquete(
        @WebParam(name = "arg0", partName = "arg0")
        Paquete arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1);

    /**
     * 
     * @return
     *     returns controladores.publicar.WrapperHashMap
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar.controladores/PublicadorManejadorUsuario/getDataUsuarioRequest", output = "http://publicar.controladores/PublicadorManejadorUsuario/getDataUsuarioResponse")
    public WrapperHashMap getDataUsuario();

}
