
package com.webservices.controladores.publicar;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "PublicadorManejadorUsuario", targetNamespace = "http://publicar.controladores/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PublicadorManejadorUsuario {


    /**
     * 
     * @param arg0
     * @return
     *     returns publicar.DataPostulante
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar.controladores/PublicadorManejadorUsuario/getDataPostulanteRequest", output = "http://publicar.controladores/PublicadorManejadorUsuario/getDataPostulanteResponse")
    public DataPostulante getDataPostulante(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns publicar.DataEmpresa
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar.controladores/PublicadorManejadorUsuario/getDataEmpresaRequest", output = "http://publicar.controladores/PublicadorManejadorUsuario/getDataEmpresaResponse")
    public DataEmpresa getDataEmpresa(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns publicar.WrapperArrayList
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar.controladores/PublicadorManejadorUsuario/obtenerOfertasFinalizadasRequest", output = "http://publicar.controladores/PublicadorManejadorUsuario/obtenerOfertasFinalizadasResponse")
    public WrapperArrayList obtenerOfertasFinalizadas(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns publicar.WrapperArrayList
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar.controladores/PublicadorManejadorUsuario/obtenerOfertasConfirmadasDeEmpresaRequest", output = "http://publicar.controladores/PublicadorManejadorUsuario/obtenerOfertasConfirmadasDeEmpresaResponse")
    public WrapperArrayList obtenerOfertasConfirmadasDeEmpresa(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns publicar.WrapperArrayList
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar.controladores/PublicadorManejadorUsuario/obtenerOfertasRechazadasIngresadasRequest", output = "http://publicar.controladores/PublicadorManejadorUsuario/obtenerOfertasRechazadasIngresadasResponse")
    public WrapperArrayList obtenerOfertasRechazadasIngresadas(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns publicar.WrapperArrayList
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar.controladores/PublicadorManejadorUsuario/obtenerOfertasDeUnaEmpresaRequest", output = "http://publicar.controladores/PublicadorManejadorUsuario/obtenerOfertasDeUnaEmpresaResponse")
    public WrapperArrayList obtenerOfertasDeUnaEmpresa(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns publicar.Postulante
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar.controladores/PublicadorManejadorUsuario/obtenerPostulanteRequest", output = "http://publicar.controladores/PublicadorManejadorUsuario/obtenerPostulanteResponse")
    public Postulante obtenerPostulante(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @Action(input = "http://publicar.controladores/PublicadorManejadorUsuario/addUsuarioRequest", output = "http://publicar.controladores/PublicadorManejadorUsuario/addUsuarioResponse")
    public void addUsuario(
        @WebParam(name = "arg0", partName = "arg0")
        DataUsuario arg0);

    /**
     * 
     * @return
     *     returns publicar.WrapperHashMap
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar.controladores/PublicadorManejadorUsuario/getDataEmpresasRequest", output = "http://publicar.controladores/PublicadorManejadorUsuario/getDataEmpresasResponse")
    public WrapperHashMap getDataEmpresas();

    /**
     * 
     * @return
     *     returns publicar.WrapperHashMap
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar.controladores/PublicadorManejadorUsuario/getDataUsuarioRequest", output = "http://publicar.controladores/PublicadorManejadorUsuario/getDataUsuarioResponse")
    public WrapperHashMap getDataUsuario();

    /**
     * 
     * @return
     *     returns publicar.WrapperHashMap
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar.controladores/PublicadorManejadorUsuario/getDataPostulantesRequest", output = "http://publicar.controladores/PublicadorManejadorUsuario/getDataPostulantesResponse")
    public WrapperHashMap getDataPostulantes();

    /**
     * 
     * @param arg0
     * @param arg1
     */
    @WebMethod
    @Action(input = "http://publicar.controladores/PublicadorManejadorUsuario/agregarSeguidorRequest", output = "http://publicar.controladores/PublicadorManejadorUsuario/agregarSeguidorResponse")
    public void agregarSeguidor(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1);

    /**
     * 
     * @param arg0
     * @param arg1
     */
    @WebMethod
    @Action(input = "http://publicar.controladores/PublicadorManejadorUsuario/quitarSeguidorRequest", output = "http://publicar.controladores/PublicadorManejadorUsuario/quitarSeguidorResponse")
    public void quitarSeguidor(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar.controladores/PublicadorManejadorUsuario/obtenerNombrePaqueteRequest", output = "http://publicar.controladores/PublicadorManejadorUsuario/obtenerNombrePaqueteResponse")
    public String obtenerNombrePaquete(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar.controladores/PublicadorManejadorUsuario/tienePaquetePreguntaRequest", output = "http://publicar.controladores/PublicadorManejadorUsuario/tienePaquetePreguntaResponse")
    public String tienePaquetePregunta(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns publicar.WrapperArrayList
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar.controladores/PublicadorManejadorUsuario/obtenerDataOfertasDeEmpresaRequest", output = "http://publicar.controladores/PublicadorManejadorUsuario/obtenerDataOfertasDeEmpresaResponse")
    public WrapperArrayList obtenerDataOfertasDeEmpresa(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns publicar.DataPostulacion
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar.controladores/PublicadorManejadorUsuario/obtenerDataPostulacionRequest", output = "http://publicar.controladores/PublicadorManejadorUsuario/obtenerDataPostulacionResponse")
    public DataPostulacion obtenerDataPostulacion(
        @WebParam(name = "arg0", partName = "arg0")
        Postulacion arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns publicar.DataUsuario
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar.controladores/PublicadorManejadorUsuario/obtenerDataUsuarioPorEmailRequest", output = "http://publicar.controladores/PublicadorManejadorUsuario/obtenerDataUsuarioPorEmailResponse")
    public DataUsuario obtenerDataUsuarioPorEmail(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns publicar.WrapperArrayList
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar.controladores/PublicadorManejadorUsuario/obtenerDataPostulacionesRequest", output = "http://publicar.controladores/PublicadorManejadorUsuario/obtenerDataPostulacionesResponse")
    public WrapperArrayList obtenerDataPostulaciones(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns publicar.WrapperArrayList
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar.controladores/PublicadorManejadorUsuario/obtenerDataPaquetesRequest", output = "http://publicar.controladores/PublicadorManejadorUsuario/obtenerDataPaquetesResponse")
    public WrapperArrayList obtenerDataPaquetes(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns publicar.WrapperArrayList
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar.controladores/PublicadorManejadorUsuario/obtenerDataOfertasDePostulacionesRequest", output = "http://publicar.controladores/PublicadorManejadorUsuario/obtenerDataOfertasDePostulacionesResponse")
    public WrapperArrayList obtenerDataOfertasDePostulaciones(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns publicar.Empresa
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar.controladores/PublicadorManejadorUsuario/obteneraEmpresaRequest", output = "http://publicar.controladores/PublicadorManejadorUsuario/obteneraEmpresaResponse")
    public Empresa obteneraEmpresa(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg2
     * @param arg3
     */
    @WebMethod(operationName = "CompraPaquete")
    @Action(input = "http://publicar.controladores/PublicadorManejadorUsuario/CompraPaqueteRequest", output = "http://publicar.controladores/PublicadorManejadorUsuario/CompraPaqueteResponse")
    public void compraPaquete(
        @WebParam(name = "arg0", partName = "arg0")
        Paquete arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2,
        @WebParam(name = "arg3", partName = "arg3")
        String arg3);

    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg2
     */
    @WebMethod(operationName = "CompraDePaquete")
    @Action(input = "http://publicar.controladores/PublicadorManejadorUsuario/CompraDePaqueteRequest", output = "http://publicar.controladores/PublicadorManejadorUsuario/CompraDePaqueteResponse")
    public void compraDePaquete(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2);

    /**
     * 
     * @param arg0
     * @return
     *     returns publicar.DataUsuario
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar.controladores/PublicadorManejadorUsuario/obtenerDataUsuarioRequest", output = "http://publicar.controladores/PublicadorManejadorUsuario/obtenerDataUsuarioResponse")
    public DataUsuario obtenerDataUsuario(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns publicar.WrapperArrayList
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar.controladores/PublicadorManejadorUsuario/obtenerSeguidoresRequest", output = "http://publicar.controladores/PublicadorManejadorUsuario/obtenerSeguidoresResponse")
    public WrapperArrayList obtenerSeguidores(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns publicar.WrapperArrayList
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar.controladores/PublicadorManejadorUsuario/obtenerSeguidosRequest", output = "http://publicar.controladores/PublicadorManejadorUsuario/obtenerSeguidosResponse")
    public WrapperArrayList obtenerSeguidos(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

}
