
package com.webservices.controladores.publicar;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;

import com.utils.Config;

import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "PublicadorControladorOfertasService", targetNamespace = "http://publicar.controladores/")
public class PublicadorControladorOfertasService
    extends Service
{

    private final static URL PUBLICADORCONTROLADOROFERTASSERVICE_WSDL_LOCATION;
    private final static WebServiceException PUBLICADORCONTROLADOROFERTASSERVICE_EXCEPTION;
    private final static QName PUBLICADORCONTROLADOROFERTASSERVICE_QNAME = new QName("http://publicar.controladores/", "PublicadorControladorOfertasService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
        	url = new URL(Config.getWebServiceBaseURL() + "/ControladorOfertas?wsdl");//url = new URL("http://localhost:9128/ControladorOfertas?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PUBLICADORCONTROLADOROFERTASSERVICE_WSDL_LOCATION = url;
        PUBLICADORCONTROLADOROFERTASSERVICE_EXCEPTION = e;
    }

    public PublicadorControladorOfertasService() {
        super(__getWsdlLocation(), PUBLICADORCONTROLADOROFERTASSERVICE_QNAME);
    }

    public PublicadorControladorOfertasService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PUBLICADORCONTROLADOROFERTASSERVICE_QNAME, features);
    }

    public PublicadorControladorOfertasService(URL wsdlLocation) {
        super(wsdlLocation, PUBLICADORCONTROLADOROFERTASSERVICE_QNAME);
    }

    public PublicadorControladorOfertasService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PUBLICADORCONTROLADOROFERTASSERVICE_QNAME, features);
    }

    public PublicadorControladorOfertasService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PublicadorControladorOfertasService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PublicadorControladorOfertas
     */
    @WebEndpoint(name = "PublicadorControladorOfertasPort")
    public PublicadorControladorOfertas getPublicadorControladorOfertasPort() {
        return super.getPort(new QName("http://publicar.controladores/", "PublicadorControladorOfertasPort"), PublicadorControladorOfertas.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PublicadorControladorOfertas
     */
    @WebEndpoint(name = "PublicadorControladorOfertasPort")
    public PublicadorControladorOfertas getPublicadorControladorOfertasPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://publicar.controladores/", "PublicadorControladorOfertasPort"), PublicadorControladorOfertas.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PUBLICADORCONTROLADOROFERTASSERVICE_EXCEPTION!= null) {
            throw PUBLICADORCONTROLADOROFERTASSERVICE_EXCEPTION;
        }
        return PUBLICADORCONTROLADOROFERTASSERVICE_WSDL_LOCATION;
    }

}
