
package com.webservices.controladores.publicar;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebFault(name = "yaExistePostulacionAOfertaException", targetNamespace = "http://publicar.controladores/")
public class YaExistePostulacionAOfertaException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private YaExistePostulacionAOfertaException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public YaExistePostulacionAOfertaException_Exception(String message, YaExistePostulacionAOfertaException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param cause
     * @param faultInfo
     * @param message
     */
    public YaExistePostulacionAOfertaException_Exception(String message, YaExistePostulacionAOfertaException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: publicar.YaExistePostulacionAOfertaException
     */
    public YaExistePostulacionAOfertaException getFaultInfo() {
        return faultInfo;
    }

}
