
package com.webservices.manejadores.publicar;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "PublicadorManejadorOfertas", targetNamespace = "http://publicar.manejadores/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PublicadorManejadorOfertas {


    /**
     * 
     * @return
     *     returns manejadores.publicar.ArrayList
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar.manejadores/PublicadorManejadorOfertas/getDataKeyWordRequest", output = "http://publicar.manejadores/PublicadorManejadorOfertas/getDataKeyWordResponse")
    public ArrayList getDataKeyWord();

    /**
     * 
     * @param arg0
     * @return
     *     returns manejadores.publicar.DataOferta
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar.manejadores/PublicadorManejadorOfertas/obtenerOfertaRequest", output = "http://publicar.manejadores/PublicadorManejadorOfertas/obtenerOfertaResponse")
    public DataOferta obtenerOferta(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @Action(input = "http://publicar.manejadores/PublicadorManejadorOfertas/addPostulacionRequest", output = "http://publicar.manejadores/PublicadorManejadorOfertas/addPostulacionResponse")
    public void addPostulacion(
        @WebParam(name = "arg0", partName = "arg0")
        Postulacion arg0);

    /**
     * 
     * @param arg0
     * @param arg1
     */
    @WebMethod
    @Action(input = "http://publicar.manejadores/PublicadorManejadorOfertas/linkearKeywordsRequest", output = "http://publicar.manejadores/PublicadorManejadorOfertas/linkearKeywordsResponse")
    public void linkearKeywords(
        @WebParam(name = "arg0", partName = "arg0")
        ArrayList arg0,
        @WebParam(name = "arg1", partName = "arg1")
        DataOferta arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar.manejadores/PublicadorManejadorOfertas/existeOfertaRequest", output = "http://publicar.manejadores/PublicadorManejadorOfertas/existeOfertaResponse")
    public boolean existeOferta(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @Action(input = "http://publicar.manejadores/PublicadorManejadorOfertas/addKeywordRequest", output = "http://publicar.manejadores/PublicadorManejadorOfertas/addKeywordResponse")
    public void addKeyword(
        @WebParam(name = "arg0", partName = "arg0")
        KeyWord arg0);

    /**
     * 
     * @return
     *     returns manejadores.publicar.ArrayList
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar.manejadores/PublicadorManejadorOfertas/getOfertasRequest", output = "http://publicar.manejadores/PublicadorManejadorOfertas/getOfertasResponse")
    public ArrayList getOfertas();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @Action(input = "http://publicar.manejadores/PublicadorManejadorOfertas/addUsuarioRequest", output = "http://publicar.manejadores/PublicadorManejadorOfertas/addUsuarioResponse")
    public void addUsuario(
        @WebParam(name = "arg0", partName = "arg0")
        OfertaLaboral arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @Action(input = "http://publicar.manejadores/PublicadorManejadorOfertas/addOfertaRequest", output = "http://publicar.manejadores/PublicadorManejadorOfertas/addOfertaResponse")
    public void addOferta(
        @WebParam(name = "arg0", partName = "arg0")
        OfertaLaboral arg0);

    /**
     * 
     * @param arg0
     * @param arg1
     * @return
     *     returns manejadores.publicar.ArrayList
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar.manejadores/PublicadorManejadorOfertas/obtenerPostulacionesRequest", output = "http://publicar.manejadores/PublicadorManejadorOfertas/obtenerPostulacionesResponse")
    public ArrayList obtenerPostulaciones(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns manejadores.publicar.ArrayList
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar.manejadores/PublicadorManejadorOfertas/obtenerOfertasConfirmadasPorKeyRequest", output = "http://publicar.manejadores/PublicadorManejadorOfertas/obtenerOfertasConfirmadasPorKeyResponse")
    public ArrayList obtenerOfertasConfirmadasPorKey(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

}
