
package com.webservices.manejadores.publicar;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "PublicadorManejadorPyT", targetNamespace = "http://publicar.manejadores/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PublicadorManejadorPyT {


    /**
     * 
     * @return
     *     returns manejadores.publicar.ArrayList
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar.manejadores/PublicadorManejadorPyT/getDataTipoPublicacionRequest", output = "http://publicar.manejadores/PublicadorManejadorPyT/getDataTipoPublicacionResponse")
    public ArrayList getDataTipoPublicacion();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @Action(input = "http://publicar.manejadores/PublicadorManejadorPyT/addTipoPublicacionRequest", output = "http://publicar.manejadores/PublicadorManejadorPyT/addTipoPublicacionResponse")
    public void addTipoPublicacion(
        @WebParam(name = "arg0", partName = "arg0")
        DataTipoPublicacion arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @Action(input = "http://publicar.manejadores/PublicadorManejadorPyT/addPaqueteRequest", output = "http://publicar.manejadores/PublicadorManejadorPyT/addPaqueteResponse")
    public void addPaquete(
        @WebParam(name = "arg0", partName = "arg0")
        DataPaquete arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar.manejadores/PublicadorManejadorPyT/tipoPubliYaExisteRequest", output = "http://publicar.manejadores/PublicadorManejadorPyT/tipoPubliYaExisteResponse")
    public boolean tipoPubliYaExiste(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns manejadores.publicar.DataPaquete
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar.manejadores/PublicadorManejadorPyT/getDataPaqueteRequest", output = "http://publicar.manejadores/PublicadorManejadorPyT/getDataPaqueteResponse")
    public DataPaquete getDataPaquete(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar.manejadores/PublicadorManejadorPyT/nombrePaqueteYaExisteRequest", output = "http://publicar.manejadores/PublicadorManejadorPyT/nombrePaqueteYaExisteResponse")
    public boolean nombrePaqueteYaExiste(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns manejadores.publicar.TipoPublicacion
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar.manejadores/PublicadorManejadorPyT/obtenerTipoPublicacionRequest", output = "http://publicar.manejadores/PublicadorManejadorPyT/obtenerTipoPublicacionResponse")
    public TipoPublicacion obtenerTipoPublicacion(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @return
     *     returns manejadores.publicar.ArrayList
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicar.manejadores/PublicadorManejadorPyT/getDataPaqueteArregloRequest", output = "http://publicar.manejadores/PublicadorManejadorPyT/getDataPaqueteArregloResponse")
    public ArrayList getDataPaqueteArreglo();

}
